export type ContentBlock =
  | { type: "paragraph"; text: string }
  | { type: "heading"; level: 2 | 3; text: string; id: string }
  | { type: "list"; items: string[]; ordered?: boolean }
  | { type: "code"; code: string; language?: string }
  | { type: "quote"; text: string };

export interface BlogPost {
  slug: string;
  title: string;
  category: string;
  tags: string[];
  excerpt: string;
  metaDescription: string;
  author: { name: string; role: string };
  publishedAt: string;
  updatedAt: string;
  relatedServiceSlugs: string[];
  body: ContentBlock[];
}

const AUTHOR = { name: "Priya Nair", role: "Senior Stripe Integration Engineer" };

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "stripe-checkout-vs-payment-element",
    title: "The Complete Guide to Stripe Checkout vs. Payment Element",
    category: "guides",
    tags: ["checkout", "payment-element"],
    excerpt: "Both let you accept payments — but they solve different problems. Here's how to choose.",
    metaDescription:
      "Stripe Checkout vs. Payment Element compared: integration effort, UI control, and which one fits your product.",
    author: AUTHOR,
    publishedAt: "2026-01-12",
    updatedAt: "2026-01-12",
    relatedServiceSlugs: ["stripe-checkout", "payment-element"],
    body: [
      { type: "paragraph", text: "Every Stripe integration eventually asks the same question: do we redirect to a hosted page, or build the payment form ourselves? The answer depends less on preference and more on how much control your product actually needs." },
      { type: "heading", level: 2, text: "When Checkout Is the Right Call", id: "when-checkout" },
      { type: "paragraph", text: "Stripe Checkout is a fully hosted page — you redirect the customer, Stripe handles the form, and you get a webhook when it's done. It's the fastest path to a working payment flow and carries the smallest PCI footprint of any integration path." },
      { type: "list", items: [
        "You want to launch in days, not weeks",
        "Your checkout doesn't need deep custom branding beyond logo/colors",
        "You'd rather not own form validation, 3DS, or wallet detection",
      ] },
      { type: "heading", level: 2, text: "When Payment Element Is Worth the Extra Work", id: "when-payment-element" },
      { type: "paragraph", text: "Payment Element renders inline, in your own page, fully styled to match your design system. It's the right call when the checkout experience is core to your product — a multi-step flow, an embedded upgrade prompt, or a native-feeling mobile web checkout." },
      { type: "paragraph", text: "The tradeoff is real: you own more of the surrounding UX (loading states, error handling, redirect-free 3DS), and your PCI scope widens slightly (usually still SAQ A-EP rather than SAQ A)." },
      { type: "heading", level: 2, text: "Our Rule of Thumb", id: "rule-of-thumb" },
      { type: "paragraph", text: "Start with Checkout unless you already know you need Payment Element. It's much easier to move from Checkout to Payment Element later than to over-build a custom form you didn't need." },
    ],
  },
  {
    slug: "stripe-nextjs-app-router-guide",
    title: "How to Add Stripe to a Next.js 15 App Router Project",
    category: "tutorials",
    tags: ["nextjs", "checkout"],
    excerpt: "Server Actions, Route Handlers, and the runtime gotcha that breaks most first attempts.",
    metaDescription:
      "A practical guide to integrating Stripe Checkout and webhooks in a Next.js 15 App Router project.",
    author: AUTHOR,
    publishedAt: "2026-01-19",
    updatedAt: "2026-01-19",
    relatedServiceSlugs: ["stripe-checkout", "webhooks", "api-integration"],
    body: [
      { type: "paragraph", text: "App Router changes the shape of a Stripe integration more than most teams expect. The old \"API routes\" mental model still mostly works, but two things trip up almost every first attempt: Server Actions for creating sessions, and the runtime configuration on your webhook handler." },
      { type: "heading", level: 2, text: "Creating a Checkout Session", id: "creating-session" },
      { type: "paragraph", text: "A Server Action is the cleanest way to create a Checkout Session from a form submission — no separate API route needed for the simple case." },
      { type: "code", language: "ts", code: `"use server";\n\nexport async function createCheckoutSession() {\n  const session = await stripe.checkout.sessions.create({\n    mode: "payment",\n    line_items: [{ price: "price_123", quantity: 1 }],\n    success_url: \`\${process.env.SITE_URL}/success\`,\n    cancel_url: \`\${process.env.SITE_URL}/cancel\`,\n  });\n  redirect(session.url!);\n}` },
      { type: "heading", level: 2, text: "The Webhook Runtime Gotcha", id: "webhook-runtime" },
      { type: "paragraph", text: "Webhook signature verification needs the raw request body and Node.js APIs — it will not work on the Edge runtime. Explicitly force the Node runtime on your webhook route." },
      { type: "code", language: "ts", code: `export const runtime = "nodejs";\n\nexport async function POST(req: Request) {\n  const body = await req.text();\n  const sig = req.headers.get("stripe-signature")!;\n  const event = stripe.webhooks.constructEvent(body, sig, process.env.STRIPE_WEBHOOK_SECRET!);\n  // handle event\n}` },
      { type: "paragraph", text: "Miss this and signature verification fails intermittently in production while working fine locally — a classic case of an environment difference masking the real bug." },
    ],
  },
  {
    slug: "handling-stripe-webhooks-nodejs",
    title: "Handling Stripe Webhooks Reliably in Node.js",
    category: "webhooks",
    tags: ["nodejs", "webhooks"],
    excerpt: "Verification, idempotency, and retries — the three things that separate a toy webhook handler from a production one.",
    metaDescription: "A practical pattern for reliable Stripe webhook handling in Node.js: verification, idempotency, and retries.",
    author: AUTHOR,
    publishedAt: "2026-01-26",
    updatedAt: "2026-01-26",
    relatedServiceSlugs: ["webhooks", "api-integration"],
    body: [
      { type: "paragraph", text: "Most webhook bugs aren't about Stripe — they're about the three things a production HTTP handler needs that a tutorial handler skips: signature verification, idempotency, and fast acknowledgment." },
      { type: "heading", level: 2, text: "Verify Before You Trust", id: "verify" },
      { type: "paragraph", text: "Never process a webhook payload without verifying its signature against your webhook secret. This is the single most common security gap we find auditing existing integrations." },
      { type: "heading", level: 2, text: "Idempotency Is Not Optional", id: "idempotency" },
      { type: "paragraph", text: "Stripe can and will deliver the same event more than once. Store processed event IDs and check them before acting — otherwise a retried webhook can double-fulfill an order or double-send a confirmation email." },
      { type: "list", items: [
        "Store event.id in a table with a unique constraint",
        "Check for existence before processing, not after",
        "Return 200 even if you've already processed the event",
      ] },
      { type: "heading", level: 2, text: "Acknowledge Fast, Process Async", id: "acknowledge" },
      { type: "paragraph", text: "Respond within a few seconds — Stripe times out and retries otherwise. If your processing is heavier than that, acknowledge immediately and hand off to a queue." },
    ],
  },
  {
    slug: "stripe-connect-standard-vs-express-vs-custom",
    title: "Stripe Connect: Standard vs. Express vs. Custom, Explained",
    category: "comparisons",
    tags: ["connect", "marketplace"],
    excerpt: "The account-type decision that's expensive to reverse — here's how to get it right the first time.",
    metaDescription: "A clear comparison of Stripe Connect Standard, Express, and Custom account types for marketplace platforms.",
    author: AUTHOR,
    publishedAt: "2026-02-02",
    updatedAt: "2026-02-02",
    relatedServiceSlugs: ["stripe-connect-standard", "stripe-connect-express", "stripe-connect-custom"],
    body: [
      { type: "paragraph", text: "Of every decision in a marketplace build, the Connect account type is the one most expensive to change after launch — it shapes your onboarding flow, your compliance obligations, and how much of the seller experience you control." },
      { type: "heading", level: 2, text: "Standard: Fastest, Least Control", id: "standard" },
      { type: "paragraph", text: "Sellers get their own full Stripe Dashboard and handle their own compliance. You take on the least liability and the least development effort, at the cost of almost no control over their experience." },
      { type: "heading", level: 2, text: "Express: The Common Middle Ground", id: "express" },
      { type: "paragraph", text: "A branded onboarding flow with Stripe still handling identity verification and compliance. This is what most two-sided marketplaces should default to." },
      { type: "heading", level: 2, text: "Custom: Full Control, Full Responsibility", id: "custom" },
      { type: "paragraph", text: "No Stripe branding anywhere, full control over onboarding and payouts — and your platform takes on meaningfully more compliance surface. Reserve this for cases where the seller experience is core to your product." },
      { type: "quote", text: "Choosing Custom by default \"for flexibility\" is the single most common over-engineering mistake we see in early-stage marketplace builds." },
    ],
  },
  {
    slug: "stripe-webhook-signature-errors",
    title: "5 Common Stripe Webhook Signature Verification Errors (and Fixes)",
    category: "error-fixes",
    tags: ["webhooks"],
    excerpt: "If your webhook signature check is failing, it's almost always one of these five causes.",
    metaDescription: "Fixes for the most common Stripe webhook signature verification errors developers encounter in production.",
    author: AUTHOR,
    publishedAt: "2026-02-09",
    updatedAt: "2026-02-09",
    relatedServiceSlugs: ["webhooks", "bug-fixes"],
    body: [
      { type: "paragraph", text: "\"No signatures found matching the expected signature\" is one of the most common Stripe errors we get asked to debug. It's almost always one of these five causes." },
      { type: "list", ordered: true, items: [
        "Body-parsing middleware (express.json(), bodyParser) runs before your webhook route and mutates the raw body Stripe needs to verify against",
        "Using the wrong webhook secret — test mode and live mode each have their own",
        "A proxy or CDN modifying the request body before it reaches your server",
        "Re-stringifying a parsed body instead of using the original raw bytes",
        "Multiple webhook endpoints configured in the Stripe Dashboard, each with a different secret",
      ] },
      { type: "heading", level: 2, text: "The Fix", id: "the-fix" },
      { type: "paragraph", text: "Get the raw request body before any JSON-parsing middleware touches it, and confirm you're using the webhook signing secret that matches the specific endpoint and mode (test vs. live) that sent the event." },
    ],
  },
  {
    slug: "stripe-test-cards-test-mode-guide",
    title: "A Developer's Guide to Stripe Test Cards and Test Mode",
    category: "testing",
    tags: ["testing"],
    excerpt: "The test card numbers, 3DS triggers, and decline codes worth actually memorizing.",
    metaDescription: "A reference guide to Stripe's test mode: test card numbers, 3D Secure triggers, and simulating declines.",
    author: AUTHOR,
    publishedAt: "2026-02-16",
    updatedAt: "2026-02-16",
    relatedServiceSlugs: ["stripe-checkout", "payment-element"],
    body: [
      { type: "paragraph", text: "Stripe's test mode is more capable than most teams use it for — beyond a generic \"successful payment\" card, you can simulate declines, 3D Secure challenges, and specific failure codes." },
      { type: "heading", level: 2, text: "The Cards Worth Memorizing", id: "cards" },
      { type: "list", items: [
        "4242 4242 4242 4242 — always succeeds",
        "4000 0000 0000 0002 — always declines (generic)",
        "4000 0025 0000 3155 — requires 3D Secure authentication",
        "4000 0000 0000 9995 — declines with insufficient_funds",
      ] },
      { type: "heading", level: 2, text: "Test Clocks for Subscription Testing", id: "test-clocks" },
      { type: "paragraph", text: "For billing logic, don't wait real days for a renewal to fire — Stripe's Test Clocks let you advance simulated time and trigger renewal, dunning, and cancellation events on demand." },
    ],
  },
  {
    slug: "stripe-api-idempotency-example",
    title: "Stripe API Idempotency: A Practical Example",
    category: "api-examples",
    tags: ["api"],
    excerpt: "Idempotency keys prevent double-charges on retry — here's exactly how to use them.",
    metaDescription: "A practical example of using idempotency keys with the Stripe API to safely retry requests without double-charging.",
    author: AUTHOR,
    publishedAt: "2026-02-23",
    updatedAt: "2026-02-23",
    relatedServiceSlugs: ["api-integration", "recurring-payments"],
    body: [
      { type: "paragraph", text: "Network requests fail. Retrying a payment creation request without protection risks charging a customer twice — idempotency keys solve this at the API level." },
      { type: "code", language: "ts", code: `await stripe.paymentIntents.create(\n  { amount: 2000, currency: "usd", customer: customerId },\n  { idempotencyKey: \`order-\${orderId}\` }\n);` },
      { type: "paragraph", text: "If the same idempotency key is sent twice, Stripe returns the original response instead of creating a second charge — even if your first request technically succeeded but your client never received the response." },
      { type: "heading", level: 2, text: "Choosing a Good Key", id: "choosing-key" },
      { type: "paragraph", text: "Tie the key to something meaningful and unique in your system — an order ID, not a random UUID generated fresh on every retry, which defeats the purpose entirely." },
    ],
  },
  {
    slug: "pci-compliance-stripe-checkout",
    title: "How PCI Compliance Actually Works When You Use Stripe Checkout",
    category: "security",
    tags: ["pci", "checkout"],
    excerpt: "Using Checkout reduces your PCI scope significantly — here's exactly what that means in practice.",
    metaDescription: "An explanation of how Stripe Checkout reduces PCI DSS scope, and what SAQ type applies to your integration.",
    author: AUTHOR,
    publishedAt: "2026-03-02",
    updatedAt: "2026-03-02",
    relatedServiceSlugs: ["pci-compliance", "stripe-checkout"],
    body: [
      { type: "paragraph", text: "\"Are we PCI compliant?\" is a question every team building on Stripe eventually asks. The honest answer depends entirely on which integration path you chose." },
      { type: "heading", level: 2, text: "Checkout: SAQ A Territory", id: "saq-a" },
      { type: "paragraph", text: "Because Checkout is a fully hosted Stripe page, your servers never touch card data — this typically qualifies you for the simplest self-assessment questionnaire, SAQ A." },
      { type: "heading", level: 2, text: "Payment Element: SAQ A-EP", id: "saq-a-ep" },
      { type: "paragraph", text: "Payment Element renders in your page, so it's technically compliant via tokenization, but the broader SAQ A-EP typically applies since your page hosts the payment form, even though card data itself never touches your servers." },
      { type: "paragraph", text: "Neither path makes PCI compliance fully automatic — you still need a completed SAQ, and organizational practices (like never logging raw card data, which Stripe never sends you anyway) still matter." },
    ],
  },
  {
    slug: "architecting-marketplace-stripe-connect",
    title: "Architecting a Multi-Sided Marketplace on Stripe Connect",
    category: "architecture",
    tags: ["connect", "marketplace"],
    excerpt: "The five architectural decisions that determine whether your marketplace payments scale cleanly.",
    metaDescription: "A system-design guide to architecting a multi-sided marketplace on Stripe Connect, from account types to payout timing.",
    author: AUTHOR,
    publishedAt: "2026-03-09",
    updatedAt: "2026-03-09",
    relatedServiceSlugs: ["marketplace-development", "stripe-connect-express"],
    body: [
      { type: "paragraph", text: "A marketplace's payment architecture determines its ceiling for scale far more than its frontend stack does. Five decisions matter most." },
      { type: "list", ordered: true, items: [
        "Connect account type (Standard/Express/Custom) — sets your compliance surface",
        "Fee model — application fee vs. separate charges and transfers",
        "Payout timing — instant, daily, or scheduled per seller",
        "Refund routing — platform-funded vs. seller-funded, decided before launch",
        "Dispute handling — who absorbs a chargeback, contractually and technically",
      ] },
      { type: "heading", level: 2, text: "Why This Order Matters", id: "why-order" },
      { type: "paragraph", text: "Each decision constrains the next. Choosing Custom to maximize control, for instance, means you also own more of the dispute and compliance surface — a tradeoff that should be made deliberately, not by default." },
    ],
  },
  {
    slug: "stripe-vs-paypal-vs-braintree",
    title: "Stripe vs. PayPal vs. Braintree: A 2026 Comparison for SaaS",
    category: "comparisons",
    tags: ["comparison"],
    excerpt: "For SaaS specifically — not general e-commerce — the decision is less close than it looks.",
    metaDescription: "A 2026 comparison of Stripe, PayPal, and Braintree specifically for SaaS subscription billing use cases.",
    author: AUTHOR,
    publishedAt: "2026-03-16",
    updatedAt: "2026-03-16",
    relatedServiceSlugs: ["stripe-billing", "migration"],
    body: [
      { type: "paragraph", text: "General payment-provider comparisons tend to be vague. For SaaS subscription billing specifically, the differences are concrete and worth being direct about." },
      { type: "heading", level: 2, text: "Billing Depth", id: "billing-depth" },
      { type: "paragraph", text: "Stripe Billing supports proration, usage-based pricing, and complex plan changes natively. PayPal's subscription tooling is comparatively thin; Braintree sits in between but requires more custom logic for the same outcomes." },
      { type: "heading", level: 2, text: "Developer Experience", id: "dx" },
      { type: "paragraph", text: "Stripe's API design and documentation quality remain a meaningful advantage for engineering velocity — this compounds over the life of a product, not just at initial integration." },
      { type: "paragraph", text: "None of this makes Stripe universally \"better\" — PayPal still carries brand trust with certain consumer demographics. But for SaaS specifically, the gap is real." },
    ],
  },
  {
    slug: "migrating-braintree-to-stripe",
    title: "Migrating from Braintree to Stripe Without Losing Subscribers",
    category: "guides",
    tags: ["migration"],
    excerpt: "The single biggest risk in a billing migration is re-collecting cards. Here's how to avoid it.",
    metaDescription: "A guide to migrating subscription billing from Braintree to Stripe without forcing customers to re-enter payment details.",
    author: AUTHOR,
    publishedAt: "2026-03-23",
    updatedAt: "2026-03-23",
    relatedServiceSlugs: ["migration", "stripe-billing"],
    body: [
      { type: "paragraph", text: "The biggest risk in any billing provider migration isn't the code — it's asking every existing subscriber to re-enter their card, which reliably causes a churn spike." },
      { type: "heading", level: 2, text: "Card Migration Is Usually Possible", id: "card-migration" },
      { type: "paragraph", text: "Stripe supports importing tokenized payment methods from several providers through a data migration process. This preserves the ability to charge existing customers without them taking any action." },
      { type: "heading", level: 2, text: "Dual-Running the Cutover", id: "dual-running" },
      { type: "paragraph", text: "Rather than a hard cutover, we typically run both systems in parallel briefly — new subscribers go to Stripe immediately, existing subscribers migrate on their next renewal cycle, with reconciliation checks at each step." },
    ],
  },
  {
    slug: "stripe-billing-proration-explained",
    title: "Stripe Billing: How Proration Actually Works",
    category: "guides",
    tags: ["billing"],
    excerpt: "Proration is where most custom billing bugs live. Here's the mental model that actually holds up.",
    metaDescription: "An explanation of how Stripe Billing calculates proration on plan upgrades and downgrades.",
    author: AUTHOR,
    publishedAt: "2026-03-30",
    updatedAt: "2026-03-30",
    relatedServiceSlugs: ["stripe-billing", "recurring-payments"],
    body: [
      { type: "paragraph", text: "Proration confuses more billing implementations than any other single concept — mostly because teams reason about it in terms of \"days used\" rather than what Stripe actually does." },
      { type: "heading", level: 2, text: "The Actual Model", id: "actual-model" },
      { type: "paragraph", text: "When a subscription changes mid-cycle, Stripe credits the unused time on the old price and charges for the remaining time on the new price — both calculated to the second, added as line items on the next invoice by default." },
      { type: "heading", level: 2, text: "The Common Mistake", id: "common-mistake" },
      { type: "paragraph", text: "Teams often try to calculate proration manually and pass a fixed amount, fighting against Stripe's built-in logic instead of configuring `proration_behavior` correctly for their use case." },
    ],
  },
  {
    slug: "stripe-laravel-integration-guide",
    title: "Integrating Stripe with Laravel: A Step-by-Step Guide",
    category: "tutorials",
    tags: ["laravel"],
    excerpt: "When to reach for Cashier, and when to go straight to the Stripe PHP SDK instead.",
    metaDescription: "A step-by-step guide to integrating Stripe with Laravel, covering both Cashier and direct SDK approaches.",
    author: AUTHOR,
    publishedAt: "2026-04-06",
    updatedAt: "2026-04-06",
    relatedServiceSlugs: ["stripe-billing", "webhooks"],
    body: [
      { type: "paragraph", text: "Laravel Cashier is often the right starting point for Stripe billing — but knowing when to step outside it matters just as much as knowing how to set it up." },
      { type: "heading", level: 2, text: "Setting Up Cashier", id: "setup-cashier" },
      { type: "paragraph", text: "Cashier wraps subscription creation, invoice access, and webhook handling behind Eloquent-friendly methods on your User model, cutting significant boilerplate for standard subscription models." },
      { type: "heading", level: 2, text: "When to Go Around It", id: "going-around" },
      { type: "paragraph", text: "Usage-based pricing, multi-party Connect payouts, or highly custom proration rules typically don't fit Cashier's conventions cleanly — at that point, working directly against the Stripe PHP SDK gives you more control with less fighting the abstraction." },
    ],
  },
  {
    slug: "stripe-shopify-beyond-default-plugin",
    title: "Adding Stripe Payments to a Shopify Store Beyond the Default Plugin",
    category: "tutorials",
    tags: ["shopify"],
    excerpt: "Shopify Payments covers standard storefronts well — here's where it stops being enough.",
    metaDescription: "A guide to custom Stripe integration for Shopify stores that need more than Shopify Payments provides.",
    author: AUTHOR,
    publishedAt: "2026-04-13",
    updatedAt: "2026-04-13",
    relatedServiceSlugs: ["stripe-connect-express", "stripe-billing"],
    body: [
      { type: "paragraph", text: "Shopify Payments, built on Stripe, is a solid default for a standard storefront. It stops being enough the moment your business model includes multi-vendor payouts or non-standard subscription logic." },
      { type: "heading", level: 2, text: "Where the Plugin Falls Short", id: "plugin-limits" },
      { type: "list", items: [
        "Multi-vendor marketplaces needing split payouts",
        "Custom subscription billing rules beyond Shopify's native options",
        "Non-standard checkout flows requiring Payment Element-level control",
      ] },
      { type: "heading", level: 2, text: "The Typical Approach", id: "typical-approach" },
      { type: "paragraph", text: "We usually integrate a custom backend service alongside Shopify — using Shopify's webhooks for order events and a direct Stripe Connect integration for payout logic the native plugin doesn't support." },
    ],
  },
  {
    slug: "debugging-stripe-paymentintent-errors",
    title: "Debugging \"No Such PaymentIntent\" and Other Common Stripe API Errors",
    category: "error-fixes",
    tags: ["api"],
    excerpt: "Most of these errors trace back to a test/live key mismatch or a stale client-side reference.",
    metaDescription: "Fixes for common Stripe API errors including 'No such PaymentIntent', mismatched keys, and stale references.",
    author: AUTHOR,
    publishedAt: "2026-04-20",
    updatedAt: "2026-04-20",
    relatedServiceSlugs: ["bug-fixes", "api-integration"],
    body: [
      { type: "paragraph", text: "\"No such PaymentIntent: pi_...\" is deceptively simple-looking but usually points to one of a small set of root causes." },
      { type: "list", items: [
        "The PaymentIntent was created in test mode but you're querying with a live key (or vice versa)",
        "The client is holding a stale PaymentIntent ID from a previous, expired session",
        "The PaymentIntent belongs to a different connected account than the one you're querying against",
      ] },
      { type: "heading", level: 2, text: "How We Debug These", id: "how-we-debug" },
      { type: "paragraph", text: "Check the mode (test/live) and, for Connect integrations, the `Stripe-Account` header first — these two account for the large majority of \"not found\" errors we're asked to fix." },
    ],
  },
  {
    slug: "stripe-radar-fraud-rule-tuning",
    title: "Stripe Radar: How to Tune Fraud Rules Without Losing Real Customers",
    category: "best-practices",
    tags: ["radar", "fraud"],
    excerpt: "Radar's defaults are a starting point, not a finished configuration.",
    metaDescription: "Best practices for tuning Stripe Radar fraud rules to reduce chargebacks without over-blocking legitimate customers.",
    author: AUTHOR,
    publishedAt: "2026-04-27",
    updatedAt: "2026-04-27",
    relatedServiceSlugs: ["stripe-radar", "security-review"],
    body: [
      { type: "paragraph", text: "Radar's default rules are tuned for the average Stripe business — which means they're not tuned for yours. Over-blocking legitimate customers is as costly as under-blocking fraud, just less visible on a dashboard." },
      { type: "heading", level: 2, text: "Start With Your Own Data", id: "own-data" },
      { type: "paragraph", text: "Before writing custom rules, review your actual chargeback and false-decline history — tuning blind against generic best practices tends to overcorrect in one direction." },
      { type: "heading", level: 2, text: "Treat It as Ongoing, Not One-Time", id: "ongoing" },
      { type: "paragraph", text: "Fraud patterns shift. Rules that were correctly tuned at launch often need revisiting as your customer base and average order value change." },
    ],
  },
  {
    slug: "marketplace-refunds-across-two-parties",
    title: "Stripe for Marketplaces: Handling Refunds Across Two Parties",
    category: "guides",
    tags: ["connect", "marketplace"],
    excerpt: "Refunds are the most commonly under-designed part of a marketplace payment architecture.",
    metaDescription: "A guide to architecting refund logic for two-sided marketplaces built on Stripe Connect.",
    author: AUTHOR,
    publishedAt: "2026-05-04",
    updatedAt: "2026-05-04",
    relatedServiceSlugs: ["marketplace-development", "stripe-connect-standard"],
    body: [
      { type: "paragraph", text: "A refund on a marketplace transaction touches three parties — buyer, seller, and platform — and someone has to decide, explicitly, who funds it." },
      { type: "heading", level: 2, text: "Platform-Funded vs. Seller-Funded", id: "funded-by" },
      { type: "paragraph", text: "Platform-funded refunds are simpler to implement but expose you to absorbing losses on seller-caused refunds. Seller-funded refunds are fairer but require pulling funds back from a seller's balance, which can fail if they've already been paid out." },
      { type: "heading", level: 2, text: "Design This Before Launch", id: "design-before-launch" },
      { type: "paragraph", text: "This decision affects your Terms of Service, your payout timing, and your dispute-handling code — retrofitting it after launch is significantly more expensive than deciding upfront." },
    ],
  },
  {
    slug: "testing-stripe-webhooks-locally-cli",
    title: "How to Test Stripe Webhooks Locally with the Stripe CLI",
    category: "testing",
    tags: ["webhooks", "testing"],
    excerpt: "Stop deploying to test webhooks — the CLI forwards real events straight to your local server.",
    metaDescription: "A guide to using the Stripe CLI to forward webhook events to your local development server for testing.",
    author: AUTHOR,
    publishedAt: "2026-05-11",
    updatedAt: "2026-05-11",
    relatedServiceSlugs: ["webhooks", "performance-optimization"],
    body: [
      { type: "paragraph", text: "Deploying to a staging environment just to test a webhook handler is slow and unnecessary — the Stripe CLI forwards real webhook events directly to your local machine." },
      { type: "code", language: "bash", code: "stripe listen --forward-to localhost:3000/api/webhooks/stripe" },
      { type: "paragraph", text: "This prints a webhook signing secret scoped to your local session — use it as your local `STRIPE_WEBHOOK_SECRET` so signature verification works exactly as it would in production." },
      { type: "heading", level: 2, text: "Triggering Specific Events", id: "triggering-events" },
      { type: "paragraph", text: "You can also trigger specific event types on demand without performing a real action in the Dashboard, which is useful for testing edge cases like disputes or failed renewals." },
      { type: "code", language: "bash", code: "stripe trigger payment_intent.payment_failed" },
    ],
  },
  {
    slug: "stripe-tax-vs-manual-calculation",
    title: "Stripe Tax vs. Manual Tax Calculation: When Automation Is Worth It",
    category: "guides",
    tags: ["tax"],
    excerpt: "Manual tax tables work fine until they don't. Here's the point where automation pays for itself.",
    metaDescription: "A comparison of Stripe Tax automated calculation versus manual tax tables, and when to switch.",
    author: AUTHOR,
    publishedAt: "2026-05-18",
    updatedAt: "2026-05-18",
    relatedServiceSlugs: ["stripe-tax", "stripe-invoicing"],
    body: [
      { type: "paragraph", text: "A hardcoded tax table is a reasonable choice for a single-state, single-country business. It stops being reasonable the moment you're registered in multiple jurisdictions with different, changing rates." },
      { type: "heading", level: 2, text: "The Manual Maintenance Cost", id: "manual-cost" },
      { type: "paragraph", text: "Tax rates and rules change more often than most teams expect, and getting them wrong carries real audit risk — this maintenance burden is what Stripe Tax is actually solving, not just calculation convenience." },
      { type: "heading", level: 2, text: "Where Manual Still Makes Sense", id: "manual-still-fine" },
      { type: "paragraph", text: "Single-jurisdiction businesses with stable rates and no near-term expansion plans may not see enough value to justify the switch yet — it's worth revisiting as you expand markets, not necessarily on day one." },
    ],
  },
  {
    slug: "stripe-security-checklist",
    title: "Stripe Security Checklist: 12 Things Most Integrations Get Wrong",
    category: "security",
    tags: ["security"],
    excerpt: "A checklist built from real security reviews, not a generic best-practices list.",
    metaDescription: "A 12-point Stripe security checklist covering API key handling, webhook verification, and common exposure risks.",
    author: AUTHOR,
    publishedAt: "2026-05-25",
    updatedAt: "2026-05-25",
    relatedServiceSlugs: ["security-review", "pci-compliance"],
    body: [
      { type: "paragraph", text: "These twelve items come directly from patterns we see repeatedly during security reviews — not a generic checklist copied from documentation." },
      { type: "list", ordered: true, items: [
        "Secret keys committed to version control history, even if later removed",
        "Publishable key used where a secret key operation was actually needed",
        "Webhook signature verification skipped or done against the wrong secret",
        "Client-side code trusting amounts sent from the browser instead of the server",
        "No idempotency keys on payment-creation requests",
        "Test-mode keys left active in a production environment",
        "Overly broad restricted API key permissions",
        "No monitoring/alerting on webhook failures",
        "Customer PII logged alongside Stripe object IDs unnecessarily",
        "No rate limiting on public-facing payment-adjacent endpoints",
        "Refund/cancellation endpoints missing authorization checks",
        "Radar rules never reviewed after initial setup",
      ] },
      { type: "paragraph", text: "Most of these are fast to fix once identified — the risk is in not knowing they exist until an audit (or an incident) surfaces them." },
    ],
  },
];
